# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-05 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190105_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['id'], 'permissions': (('view_user', '查看用户'),), 'verbose_name': '用户'},
        ),
    ]
