# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 03:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='厂商名称', max_length=32, unique=True, verbose_name='厂商名称')),
                ('address', models.CharField(default='null', help_text='厂商地址', max_length=256, verbose_name='厂商地址')),
                ('phone', models.CharField(default='null', help_text='厂商对接人电话', max_length=15, verbose_name='厂商对接人电话')),
                ('email', models.EmailField(default='null', help_text='厂商对接人邮箱地址', max_length=254, verbose_name='厂商对接人邮箱地址')),
                ('letter', models.CharField(db_index=True, default='null', help_text='厂商简称', max_length=30, unique=True, verbose_name='厂商简称')),
                ('remark', models.CharField(blank=True, help_text='备注说明', max_length=255, null=True, verbose_name='备注说明')),
            ],
            options={
                'verbose_name': '厂商',
                'db_table': 'idc',
                'ordering': ['id'],
                'permissions': (('view_idc', '查看厂商'),),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=32, verbose_name='项目名称')),
                ('pid', models.IntegerField(db_index=True, default=0, help_text='上级业务线id', verbose_name='上级业务线id')),
                ('dev_interface', models.ManyToManyField(help_text='开发接口人', related_name='dev_interface', to=settings.AUTH_USER_MODEL, verbose_name='开发接口人')),
                ('idc', models.ManyToManyField(help_text='所属厂商', related_name='product_idc', to='cmdb.Idc', verbose_name='所属厂商')),
                ('ops_interface', models.ManyToManyField(help_text='运维接口人', related_name='ops_interface', to=settings.AUTH_USER_MODEL, verbose_name='运维接口人')),
                ('product_interface', models.ManyToManyField(help_text='项目接口人', related_name='product_interface', to=settings.AUTH_USER_MODEL, verbose_name='项目接口人')),
            ],
            options={
                'verbose_name': '业务',
                'db_table': 'products',
                'ordering': ['id'],
                'permissions': (('view_product', '查看业务线'),),
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, help_text='主机名', max_length=50, null=True, verbose_name='主机名')),
                ('InstanceId', models.CharField(db_index=True, help_text='实例ID', max_length=150, null=True, verbose_name='实例ID')),
                ('ip', models.CharField(db_index=True, help_text='IP地址', max_length=100, verbose_name='IP地址')),
                ('cpu', models.CharField(help_text='cpu核数', max_length=10, null=True, verbose_name='cpu核数')),
                ('memory', models.CharField(help_text='内存', max_length=30, null=True, verbose_name='内存')),
                ('devices', models.CharField(help_text='磁盘', max_length=200, null=True, verbose_name='磁盘')),
                ('status', models.CharField(db_index=True, help_text='服务器状态', max_length=32, null=True, verbose_name='服务器状态')),
                ('os', models.CharField(db_index=True, help_text='系统', max_length=100, null=True, verbose_name='系统')),
                ('LastCheck', models.DateTimeField(auto_now=True, db_index=True, help_text='检测时间', verbose_name='检测时间')),
                ('remark', models.CharField(help_text='服务器备注', max_length=300, null=True, verbose_name='服务器备注')),
                ('idc', models.ForeignKey(help_text='主机对应IDC', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_idc', to='cmdb.Idc', verbose_name='主机对应的idc')),
                ('product', models.ForeignKey(help_text='所属项目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_product', to='cmdb.Product', verbose_name='项目')),
                ('service', models.ForeignKey(help_text='所属服务', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_service', to='cmdb.Product', verbose_name='服务')),
            ],
            options={
                'verbose_name': '服务器',
                'db_table': 'servers',
                'ordering': ['id'],
                'permissions': (('view_server', '查看服务器'),),
            },
        ),
    ]
