# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-05 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='env',
            options={'ordering': ['id'], 'permissions': (('view_env', '查看环境'),), 'verbose_name': '环境表'},
        ),
        migrations.AlterModelOptions(
            name='idc',
            options={'ordering': ['id'], 'permissions': (('view_idc', '查看机房'),), 'verbose_name': '厂商表'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'permissions': (('view_product', '查看业务线'),)},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['id'], 'permissions': (('view_server', '产看服务器'),), 'verbose_name': '服务器表'},
        ),
    ]
