# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0006_auto_20180210_1226'),
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(help_text='执行用户', max_length=50, null=True, verbose_name='执行用户')),
                ('server', models.ForeignKey(help_text='服务器', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Server', verbose_name='服务器')),
                ('task_profile', models.OneToOneField(help_text='PeriodicTask添加字段', on_delete=django.db.models.deletion.CASCADE, related_name='task_profile', to='django_celery_beat.PeriodicTask')),
            ],
            options={
                'verbose_name': 'task任务衍生表',
                'db_table': 'task_profile',
                'ordering': ['id'],
                'permissions': (('view_task_profile', 'cat view task_profile'),),
            },
        ),
    ]
