# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-04 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_batchtasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchtasks',
            options={'ordering': ['-add_time'], 'verbose_name': '批量任务', 'verbose_name_plural': '批量任务'},
        ),
    ]
