# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-04 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190104_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchtasks',
            options={'ordering': ['-add_time'], 'permissions': (('view_batchTask', 'cat view batchTask'),), 'verbose_name': '批量任务', 'verbose_name_plural': '批量任务'},
        ),
    ]
