# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-05 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20190104_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchtasks',
            options={'ordering': ['-add_time'], 'permissions': (('view_batchTask', '查看批量任务'),), 'verbose_name': '批量任务', 'verbose_name_plural': '批量任务'},
        ),
        migrations.AlterModelOptions(
            name='taskprofile',
            options={'ordering': ['id'], 'permissions': (('view_task_profile', '查看任务'),), 'verbose_name': 'task任务衍生表'},
        ),
    ]
