# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-05 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20190105_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtasks',
            name='user',
            field=models.CharField(help_text='执行用户', max_length=50, null=True, verbose_name='执行用户'),
        ),
    ]
